# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b2844a4594cb7b637db45c3e3bceb9c2522917772a3093ed2bd4a185d7c2cf307fab4314d7402655bf78b5ed48cee071aad86e24117fa92733428c5bd37e9e7

test:
  secret_key_base: 79a08d9ab0ff6ae02ed16aa7915ea4e40b7901155ab80aca7bceb2e6e6c354c72396b0fe94b59849228dbc06686d257ca02e76c16540f3c422d683676c1410e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
